#!/usr/bin/env bash

# Replace the default NGINX configuration to listen on port 80
rm /etc/nginx/sites-enabled/default

# Add a configuration to listen on all active IPv4 addresses
ln -m  /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 

# Restart NGINX service to apply the changes
service nginx restart
